export const headerSlider = [
     "US MUSLIM ADVOCACY GROUP LAUNCHES REPORT REVEALING WHOLESALE TARGETING OF MUSLIMS IN FBI TERRORISM WATCH LISTS",
     "EID AL-ADHA AND HAJJ DATES CONFIRMED",
     "RELATIVES AND WORLD LEADERS MOURN THE TRAGIC LOSS OF LIFE AS MIGRANT BOAT SINKS OFF GREEK"
]